block.settings.sponsors_by_level:
  type: block_settings
  label: 'Sponsors by Level block settings'
  mapping:
    sponsorship_level_term:
      type: integer
      label: 'Sponsorship level taxonomy term'
